# context_enriched_response_generation.py
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

import warnings
warnings.filterwarnings("ignore", category=FutureWarning, module="torch")

class ContextEnrichedResponder:
    def __init__(self, text: str):
        # Split into chunks (sentences for simplicity)
        self.sentences = [s.strip() for s in text.split(".") if s.strip()]

        # Embedding model (local, no API key needed)
        self.model = SentenceTransformer("all-MiniLM-L6-v2")

        # Encode sentences into embeddings
        self.embeddings = self.model.encode(self.sentences)

        # Build FAISS index for similarity search
        d = self.embeddings.shape[1]
        self.index = faiss.IndexFlatL2(d)
        self.index.add(np.array(self.embeddings).astype("float32")) # type: ignore

    def retrieve(self, query: str, k: int = 2):
        """Find top-k most relevant sentences"""
        q_emb = self.model.encode([query])
        D, I = self.index.search(np.array(q_emb).astype("float32"), k) # type: ignore
        return [self.sentences[i] for i in I[0]]

    def respond(self, query: str, k: int = 2) -> str:
        # Retrieve relevant context
        retrieved = self.retrieve(query, k=k)
        enriched_answer = " ".join(retrieved) if retrieved else "No relevant info found."
        return enriched_answer


if __name__ == "__main__":
    # Example document
    sample_text = """
    Retrieval-Augmented Generation (RAG) is an AI technique that combines
    information retrieval with text generation. It improves factual accuracy
    by grounding answers in external knowledge sources. RAG reduces 
    hallucinations, which are false or made-up outputs generated by AI models.
    This makes it especially useful for applications like chatbots, search 
    assistants, and knowledge-intensive question answering.
    """

    bot = ContextEnrichedResponder(sample_text)

    #   Example query
    print("Q: What is RAG?")
    print("A:", bot.respond("What is RAG?", k=2))
    
    
